### ISSUE TITLE
admin.cgi get_workgroup function assumes there is a user_id defined. Add case for getting all workgroups in admin panels

### ISSUE THREAD

**Issue by DMack98** [GlobalNOC/OESS#1222] opened 2020-10-12 14:25 UTC
https://github.com/GlobalNOC/OESS/blob/c1cd89a926f35032b6c2cca772610cbefa7bf559/frontend/webservice/admin/admin.cgi#L1210-L1214

**Comment by jonstout** [comment] 2020-11-06 16:06
Duplicate of #1220

**Closed by jonstout** 2020-11-06 16:06 UTC
