### ISSUE TITLE
Unable to provision vlan by entity if an interface has no avalable vlan ids

### ISSUE THREAD

**Issue by khood5** [GlobalNOC/OESS#1280] opened 2021-06-16 21:49 UTC
When provisioning a new vlan, adding endpoints by entity if more then one interface is associated with that entity and one of the interfaces has no available vlans then use that entity to add any endpoints, even if others have available vlans.  

see ticket SCTASK0075189 for more details.

**Comment by jonstout** [comment] 2021-06-17 13:23
Duplicate of #1233. Closing.

**Closed by jonstout** 2021-06-17 13:23 UTC
Labels: Bug, Duplicate, Frontend
